title: "WWHO: What is it, Where is it, How much? Okay!" # your name (or website title) here
logo: "/images/logoringlarge.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  WWHO is a peer to peer rental marketplace for college students. 
  This website serves as a display of our 3 year experiment and the efforts taken to bring this product to fruition. 
  <br><br>
  The WWHO marketplace is currently inactive. Through the different iterations of our product, we've learned that our market was not ready 
  for item sharing. The product market fit could not be satisfied due to Fairleigh Dickinson University's small, commuter biased market.
  Although our service solved the inherent problem of needing an item temporarily, there was not enough transactional volume to sustain growth. 
  
  <br><br>
  <a href="https://www.linkedin.com/in/nafijur-dalim-0262ba119/">LinkedIn Profile</a> 
  
  <a href="https://www.instagram.com/thewwhoteam/">Instagram Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
